### ISSUE TITLE
Unknown specialization

### ISSUE THREAD

**Issue by VenoushCZ** [StjerneIdioten/AdjustableMirrors#41]
Hi! There are errors in the log (MP dedi server session) like this:

Error: Vehicle type 'xxx' has unknown specialization 'AdjustableMirrors'!

Is it OK?

Thank you

**Comment by StjerneIdioten** [comment]
I will probably need a bit more info on your setup to determine anything about that error. I will check with my own dedi-server though just to make sure.

**Comment by StjerneIdioten** [comment]
I have looked at it and it is probably due to at what times different mods register themselves. My mod takes a very casual approach, but other mods that inspect the vehichles might not agree. If the mod still works for your vehichles, then the error message doesn't matter.

**Comment by VenoushCZ** [comment]
Hi! Mod does not work if it shows error :-(. I checked scripts that are included in the mod that is working fine and the mod that is giving this error. There is no logic behind it. Custom scripts are the same and still one is working and the other not. It has to do something with the thing you are writing about. Is there a way I can help with debugging?

One more thing: is there a way I can build the mod directly into the vehicle?

Thank you


VenoushCZ

**Comment by StjerneIdioten** [comment]
Hmm, I checked on my own server as well and it seems that it does not work if a mod specifies an ultra specific vehicle type for itself, instead of using the default ones. Back when the mod was created people really didn't do that, but I can see that the mods works fine for any other 'normal' vehicles. 
I might have to look at it again soon, I can see that a lot of things have changed as well regarding the workflow of making mods, so I might give it another chance ;-)

Regarding building it in. 
One of my original intentions was to create a version that could both be built in and automatically add itself to other vehicles. In the built in case I was interested in making it so that you could actually physically move the whole mirror assembly, instead of the sort of hack I have to do with generic vehicles ;-) But once I started to investigate into doing blender mods myself to test this out, I noticed that the blender exporter itself was lacking some much needed love. So I am kind of caught up in reworking that at the moment. 

I will return to fix stuff with the Adjustable Mirrors mod at some point, but at the moment the blender exporter is more important.

And I don't think I need much else debugging vise, since I can replicate it on my own setup as well. But only for specific mods that register their own types.

**Comment by VenoushCZ** [comment]
I get it :-) No problem, still very good to know that you care a someday maybe it will be fixed 👍 

Thank you for your time

**Comment by StjerneIdioten** [comment]
Well of course. As long as Giants refuse to put in proper adjustable mirrors I will keep this thing updated ;-)

**Comment by VenoushCZ** [comment]
Hi :-) Looks like you are just finishing the Blender exporter project... maybe you will get to the fixing of the mirrors anytime soon? Just politely asking, no pressure :-) 

Thank you!

**Comment by StjerneIdioten** [comment]
I don't know where you have been looking then :-P But yes, the exporter is progressing nicely. I have two months of summer vacation now before going back to university, so I should be able to look at the mirrors ;-)

**Comment by VenoushCZ** [comment]
Excellent news :-) Thank you! :-)

**Comment by fcucino** [comment]
The fix to the described issue is already committed to the [vehicle_registration_fix branch](https://github.com/StjerneIdioten/AdjustableMirrors/commits/vehicle_registration_fix).

I use that version since last year and I never saw that error anymore. 
(I could write the code a lot better now, but it's working)

**Comment by VenoushCZ** [comment]
You are right! Everyday I learn something new about github :-) Thank you!

**Comment by StjerneIdioten** [comment]
This just underlines that I really need to revisit this at some point 😂 Didn't even recall that branch existing. I should probably get that to the modhub version at some point.

**Comment by dbump** [comment]
That would be excellent (a new official modhub version)!  But glad to see there's another way to get this excellent mod working on all of my vehicles!
